### ISSUE TITLE
Level Shifter

### ISSUE THREAD

**Issue by ygator** [denvera/dscmod#1]
I have ordered this level shifter from banggood.
http://www.banggood.com/Logic-Level-Converter-Bi-Directional-IIC-4-Way-Level-Conversion-Module-p-938774.html
I plan to hook my DSC-PC1550 to 
http://www.banggood.com/WeMos-D1-Mini-V2-NodeMcu-4M-Bytes-Lua-WIFI-Internet-Of-Things-Development-Board-Based-ESP8266-p-1115398.html

I asked if the level shifter can do 12V to 3.3V and they said it can't.  It appears to be the same as the ones linked.  Can anyone confirm if this will work?

If not I have found another circuit that uses a 10K resistor and a BC547, but it would not be bi-directional I don't think.

Thanks

**Comment by denvera** [comment]
Hey there,

Shouldn't be a problem, I've been using an identical level shifter for well over a year now to an ESP8266. I've also used the same for connecting the KeyBus to Atemga MCUs and straight to GPIO pins without any issues, so I'd say it should be fine.

**Comment by ygator** [comment]
Thanks.  I just hooked it up a couple days ago using a voltage divider and that is working read only for now.  When the level shifter arrives I'll go ahead and try that then to get bidirectional.
